FROM docker.io/library/node:18.16-bullseye-slim as development

RUN apt update && apt install --no-install-recommends -y \
	ca-certificates \
	curl

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /home/node

ENV NODE_ENV=development

COPY package.json pnpm-lock.yaml ./

RUN pnpm fetch

COPY ./ ./

RUN pnpm install --frozen-lockfile

CMD pnpm run start:dev
